from typing import Any, List

from .cache import Cache as Cache
from .target_object.course import CourseController as CourseController
from .target_object.meta_object import Course as Course
from .target_object.meta_object import Department as Department
from .target_object.meta_object import Semester as Semester

class CourseManager:
    sem: Any = ...
    dep: Any = ...
    reuse: Any = ...
    course_list: Any = ...
    def __init__(self, sem: Semester, dep: Department, reuse: bool = ...) -> None: ...
    def run(self) -> None: ...
    prog: Any = ...
    def load_from_crawl(self) -> None: ...
    def crawl_course(self) -> None: ...
    def get_courses(self) -> List[Course]: ...
