from typing import Any

from ..fetch import fetch as fetch
from ..fetch import get_course_form_data as get_course_form_data
from .meta_object import Course as Course
from .meta_object import Department as Department
from .meta_object import Semester as Semester
from .target_object_interface import CrawlTarget as CrawlTarget
from .target_object_interface import JSONType as JSONType

class CourseController(CrawlTarget):
    sem: Any = ...
    dep: Any = ...
    data_list: Any = ...
    def __init__(self, sem: Semester, dep: Department) -> None: ...
    def crawl(self) -> None: ...
    def fetch(self) -> JSONType: ...
    def parse(self, json_data: JSONType) -> Any: ...
    def get_list(self): ...
