from typing import Any, Dict, List, Union

from typing_extensions import Protocol as Protocol

JSONType = Union[str, None, Dict[str, Any], List[Any]]

class CrawlTarget:
    def fetch(self) -> None: ...
    def parse(self, json_data: JSONType) -> Any: ...
    def crawl(self) -> None: ...
    def get_list(self) -> None: ...
