from ..objects import College as College
from ..objects import CourseCategory as CourseCategory
from ..objects import DegreeType as DegreeType
from ..objects import Department as Department
from ..type_parser import TypeParser as TypeParser

def test_parse_degree_type() -> None: ...
def test_parse_course_category() -> None: ...
def test_parse_college() -> None: ...
def test_parse_department() -> None: ...
