from typing import Any

from ..nctu_api_interactor import NCTUAPI_Interactor as NCTUAPI_Interactor
from ..objects import College as College
from ..objects import CourseCategory as CourseCategory
from ..objects import DegreeType as DegreeType
from ..objects import Semester as Semester
from ..objects import Term as Term

class QueryTarget:
    sem: Semester = ...
    deg: DegreeType = ...
    cat: CourseCategory = ...
    col: College = ...
    def __init__(self, sem: Any, deg: Any, cat: Any, col: Any) -> None: ...

def query() -> QueryTarget: ...
def nctu() -> NCTUAPI_Interactor: ...
def test_fetch_degree_type(nctu: NCTUAPI_Interactor, query: QueryTarget) -> Any: ...
def test_fetch_course_category(nctu: NCTUAPI_Interactor, query: QueryTarget) -> Any: ...
def test_fetch_colleges(nctu: NCTUAPI_Interactor, query: QueryTarget) -> Any: ...
def test_fetch_departments(nctu: NCTUAPI_Interactor, query: QueryTarget) -> Any: ...
